### ISSUE TITLE
initialValue is not a function of $mdDialog.prompt()

### ISSUE THREAD

**Issue by Stephn-R** [angular/material#8952]
**Actual Behavior**:
 -  `What is the issue?` the tool is failing to add a initial value of prompted dialogs
 -  `What is the expected behavior?`I should be able to add a initial value

**CodePen** (or steps to reproduce the issue): attempt to use the example from the docs using Angular Material v1.0.8
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: 
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.8

**Additional Information**:
 -  `Browser Type: Chrome Canary`
 -  `Browser Version: Canary Latest`
 -  `OS: Mac OSX El Capitan`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This seems to work in `v1.1.0-rc.5`.
- https://material.angularjs.org/1.1.0-rc.5/demo/dialog

Your information is mentioning, that you use the `1.0.8` version, which does not support that new functionality.

**Comment by sanori** [comment]
If the value of  the argument of `initialValue` is null string, `initialValue is not a function` error occurs.
version: angular-material@1.1.0-rc4-master-06e7e99

Is this error what you expected?
