### ISSUE TITLE
Error: node_modules/@angular/material/stepper/stepper.d.ts:39:14

### ISSUE THREAD

**Issue by rahulvish1364** [angular/material#12070]
Seeing this issue when I upgraded angular from angular 10 to 11
Seems the version of angular is not changed even if i change it manually. I see the same error
` 
    Error: node_modules/@angular/material/stepper/stepper.d.ts:39:14 - error TS2610: 'steps' is defined as an accessor in class 'CdkStepper', but is overridden her    
    39     readonly steps: QueryList<MatStep>;
                    ~~~~~`


here is my package.json

`{
  "name": "ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "sonar": "sonar-scanner"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.5",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/material": "^10.1.0",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/router": "~11.0.5",
    "@ng-idle/core": "^10.0.0-beta.1",
    "@ng-idle/keepalive": "10.0.0-beta.1",
    "angular-froala-wysiwyg": "^3.2.0",
    "angular2-moment": "^1.9.0",
    "ng-block-ui": "^3.0.2",
    "ngx-cookie": "^5.0.0",
    "ngx-device-detector": "^1.4.5",
    "rxjs": "~6.5.5",
    "sonar-scanner": "^3.1.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "~11.0.5",
    "@angular/compiler-cli": "~11.0.5",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "karma-sonarqube-unit-reporter": "0.0.21",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.5"
  }
}
`

**Comment by rahulvish1364** [comment]
`Error: node_modules/@angular/material/radio/radio.d.ts:199:9 - error TS2611: 'disabled' is defined as a property in class 'CanDisableRipple & HasTabIndex & MatRadioButtonBase', but is overridden here in '_MatRadioButtonBase' as an accessor.
    
    199     get disabled(): boolean;
                ~~~~~~~~`

Sometime seeing this. Not sure why this is happening.

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

**Comment by kcLin2708** [comment]
I've solved this issue via updating angular material.
