### ISSUE TITLE
md-select mapFn undefined

### ISSUE THREAD

**Issue by wwhurley** [angular/material#6204]
In some cases the `mapFn` variable is undefined. This leads to errors like:

```
TypeError: undefined is not a function
    at Array.map (native)
    at Object.SelectMenuController.self.selectedLabels (http://localhost:9001/vendor/js/angular-material/angular-material.js:13780:34)
    at Scope.$digest (http://localhost:9001/vendor/js/angular/angular.js:15888:40)
    at Scope.$apply (http://localhost:9001/vendor/js/angular/angular.js:16160:24)
    at HTMLElement.clickListener (http://localhost:9001/vendor/js/angular-material/angular-material.js:13648:13)
    at HTMLElement.jQuery.event.dispatch (http://localhost:9001/vendor/js/jquery/jquery.js:4435:9)
    at HTMLElement.elemData.handle (http://localhost:9001/vendor/js/jquery/jquery.js:4121:28)
```

It appears to be caused by https://github.com/angular/material/commit/f73e5033bd4446412ca6b5ce7a769901274f4147#diff-d7b463f733c2e3fbc783f38073561b74R632 when `mode` is equal to `display`

**Comment by zainul-realtime** [comment]
yeah i have some issue like this , hopefully to be fixed

**Comment by jakubweber** [comment]
Same here, need to be fixed

**Comment by sebastiengiroux** [comment]
I have the same problem

**Comment by AquariusFR** [comment]
Same here, any clues ?

**Comment by suur** [comment]
It appears the ```opts``` in ```self.selectedLabels = function(opts) {``` sometimes has the controller scope in it's prototype so ```opts.mode``` is equal to ```$scope.mode```.

A temporary workaround for this would be not to use ```mode``` in scope.

**Comment by nicky-lenaers** [comment]
Same issue, needs to be fixed.

**Comment by nicky-lenaers** [comment]
For anyone still having this problem, I found it occurs when using ``value=""`` instead of ``ng-value=""``. Hopefully this helps some of you!

**Comment by nicky-lenaers** [comment]
Right solution by @suur confirmed working, thanks a lot!

**Comment by mzaarour** [comment]
Please patch this bug !!

**Comment by zainul-realtime** [comment]
solution is don't use $scope.mode change to another name

**Comment by mzaarour** [comment]
Thank you. 
It works when avoid using $scope.mode principaly in a whole app controller. 
However a patch will be welcome

**Comment by darkmavis1980** [comment]
+1 same issue here

**Comment by omer123456** [comment]
replace `scope.$watch(selectMenuCtrl.selectedLabels, syncLabelText);`
with:

```
scope.$watch(function() { // replaced
        return selectMenuCtrl.selectedLabels();
      }, syncLabelText); 
```

**Comment by fkpwolf** [comment]
+1 spend lots of time to find root cause.

**Comment by misherone** [comment]
Had $scope.mode in my controller. Thanks suur for your help. Waiting for better incapsulation...

**Comment by DevVersion** [comment]
This is a duplicate of #6260, which already has a PR fixing - #7830. 

I will close that issue, because the other issue, is already referenced by the PR.
